CREATE DATABASE telelink;

CREATE TABLE links (
  "id" SERIAL PRIMARY KEY,
  "url" TEXT NOT NULL,
  "title" TEXT,
  "text" TEXT,
  "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);
